// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDPZOgGkjNUlTBmJ4w6vArpa81n0tNTE',
    appId: '1:368972382746:web:0f0c3bb1b93593e93bc7a3',
    messagingSenderId: '368972382746',
    projectId: 'e-com-f0de8',
    authDomain: 'e-com-f0de8.firebaseapp.com',
    storageBucket: 'e-com-f0de8.appspot.com',
    measurementId: 'G-6JHJ4T5GQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2rN93Vm2gvgl7IWNeTdhL03u5NvouN0',
    appId: '1:368972382746:android:e129158b51005ab23bc7a3',
    messagingSenderId: '368972382746',
    projectId: 'e-com-f0de8',
    storageBucket: 'e-com-f0de8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8fu76RyAkm2aRU0tJyoORZyHRKwmULeA',
    appId: '1:368972382746:ios:2a60a81ef285d9f53bc7a3',
    messagingSenderId: '368972382746',
    projectId: 'e-com-f0de8',
    storageBucket: 'e-com-f0de8.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8fu76RyAkm2aRU0tJyoORZyHRKwmULeA',
    appId: '1:368972382746:ios:ef94ec2a0de82fb83bc7a3',
    messagingSenderId: '368972382746',
    projectId: 'e-com-f0de8',
    storageBucket: 'e-com-f0de8.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
